"""Fixed is_verified column name'

Revision ID: ffc0b6b6d80c
Revises: 9f02363b2fef
Create Date: 2024-11-16 19:43:12.961821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'ffc0b6b6d80c'
down_revision: Union[str, None] = '9f02363b2fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
